GROUP MEMBERS :
1.  Aniruddh Shukla 
2. Gaurav Singhal 
3. Himanshi Bajaj 

In [0]:
import os
os.chdir("/content/drive/My Drive/Colab Notebooks")

In [0]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

# Task 1

In [0]:
@tf.function
def task1(twoDarr,k):
  tf.print("================= 2D Tensor of shape (?,n) before calculating top k values =================== \n")
  tf.print(twoDarr)
  newarr = tf.math.top_k(twoDarr,k=k)
  return newarr

In [0]:
twoDarr = tf.random.uniform((4,6),minval=5,maxval=50,dtype=tf.dtypes.int32)
k = 5
output = task1(twoDarr,k)
tf.print("\n ================= 2D Tensor of shape (?,k) after calculating top k values =================== \n")
tf.print(output.values)
tf.print("\n ================= Indices of resultant tensor =================== \n")
tf.print(output.indices)

================= 2D Tensor of shape (?,n) before calculating top k values =================== 

[[26 12 48 45 14 31]
 [25 41 45 31 41 48]
 [36 30 35 6 15 30]
 [45 24 38 9 22 17]]

 ================= 2D Tensor of shape (?,k) after calculating top k values =================== 

[[48 45 31 26 14]
 [48 45 41 41 31]
 [36 35 30 30 15]
 [45 38 24 22 17]]

 ================= Indices of resultant tensor =================== 

[[2 3 5 0 4]
 [5 2 1 4 3]
 [0 2 1 5 4]
 [0 2 1 4 5]]


# Task 2

In [0]:
@tf.function
def task2(twoDarr):
  tf.random.set_seed(10)
  tf.print("================= 2D Tensor of shape (?,n) before calculating argmax =================== \n")
  tf.print(twoDarr)
  newarr = tf.argmax(twoDarr,axis=1)
  return newarr

In [0]:
twoDarr = tf.random.uniform((4,5),minval=5,maxval=50,dtype=tf.dtypes.int32)
output = task2(twoDarr)
tf.print("\n ================= After calculating argmax =================== \n")
tf.print(output)
tf.print("\n ================= 2D Tensor of shape (?,n) with 0 and 1 =================== \n")
depth = twoDarr.get_shape()
output = tf.one_hot(output,depth=depth[1])
tf.print(output)

================= 2D Tensor of shape (?,n) before calculating argmax =================== 

[[22 14 31 32 37]
 [14 46 38 40 13]
 [24 5 15 47 48]
 [12 17 5 28 20]]

 ================= after calculating argmax =================== 

[4 1 4 3]

 ================= 2D Tensor of shape (?,n) with 0 and 1 =================== 

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


# Task 3 

In [0]:
@tf.function
def task3(twoDarr,k):
  newarr = tf.math.top_k(twoDarr,k=k)
  idxs = tf.expand_dims(newarr.indices,axis=1)
  # tf.print(idxs.shape)
  vals = newarr.values
  # tf.print(idxs,vals)
  scatter = tf.scatter_nd(indices=idxs,updates=vals,shape=twoDarr.shape)
  return scatter

In [0]:
twoDarr = tf.random.uniform((6,),minval=5,maxval=50,dtype=tf.dtypes.int32)
k = 3
tf.print("================= 1D Tensor of shape (n,) before calculating top k values =================== \n")
tf.print(twoDarr)
scatter = task3(twoDarr,k)
tf.print("\n ================= 1D Tensor of shape (n,) after calculating top k values and scatter =================== \n")
tf.print(scatter)

================= 1D Tensor of shape (n,) before calculating top k values =================== 

[23 40 21 40 43 12]

 ================= 1D Tensor of shape (n,) after calculating top k values and scatter =================== 

[0 40 0 40 43 0]


**Bonus**

In [0]:
# source https://stackoverflow.com/questions/52996505/using-scatter-nd-with-top-k-output
@tf.function
def task3(twoDarr,k):

  newarr = tf.math.top_k(twoDarr,k=k)
  idxs = newarr.indices
  vals = newarr.values

  # tf.print(idxs.shape)
  # tf.print(vals.shape)
  # tf.print("\n\n",idxs,"\n\n",vals)

  num_rows = twoDarr.shape[0]
  row_range = tf.range(num_rows)
  tensor_row = tf.tile(row_range[:,None], (1, k))

  # tf.print("\n",num_rows)
  # tf.print("\n",row_range)
  # tf.print("\n",row_tensor)

  top_k_row_col_idxs = tf.stack([tensor_row, idxs], axis=2)
  # tf.print("\n",top_k_row_col_indices)

  updates = tf.ones([num_rows, k], dtype=tf.int32)
  # tf.print("\n",updates)

  zero_mask = tf.scatter_nd(top_k_row_col_idxs, updates, [num_rows, 4])
  # tf.print("\n",zero_mask)

  scatter = twoDarr * zero_mask
  # tf.print("\n",scatter)
  return scatter

In [0]:
twoDarr = tf.random.uniform((3,4),minval=5,maxval=50,dtype=tf.dtypes.int32)
k = 3

tf.print("================= 2D Tensor of shape (?,n) before calculating top k values =================== \n")
tf.print(twoDarr)

output = task3(twoDarr,k)
tf.print("\n ================= 2D Tensor of shape (?,n) after calculating top k values and scatter =================== \n")
tf.print(output)

================= 2D Tensor of shape (?,n) before calculating top k values =================== 

[[19 18 10 47]
 [10 5 16 31]
 [24 37 40 15]]

 ================= 2D Tensor of shape (?,n) after calculating top k values and scatter =================== 

[[19 18 0 47]
 [10 0 16 31]
 [24 37 40 0]]


# Task 4

In [0]:
@tf.function
def task4(input,a):
  arr = tf.TensorArray(dtype=tf.float32,size=0,dynamic_size=True,clear_after_read=False)
  arr = arr.write(0,input[0])
  for idx in range(1,input.shape[0]):
    arr = arr.write(idx,(a * arr.read(idx-1) + (1-a) * input[idx]))
    new = arr.stack()
  return new

In [0]:
input = tf.range(1,6,dtype=tf.float32)
a = tf.constant(0.20)    # decay rate
tf.print("================= Input before calculating Exponentially moving Average =================== \n")
tf.print(input)
new = task4(input,a)
tf.print("================= Output after calculating Exponentially moving Average =================== \n")
tf.print(new)

================= Input before calculating Exponentially moving Average =================== 

[1 2 3 4 5]
================= Output after calculating Exponentially moving Average =================== 

[1 1.80000007 2.76000023 3.752 4.7504]


# Task 5  

In [0]:
# source - https://stackoverflow.com/questions/42869495/numpy-version-of-exponential-weighted-moving-average-equivalent-to-pandas-ewm handy0815
def task5(input, a):

    n = int(-100. / np.log(a)) # Makes sure that the first and last elements in f are very big and very small (about 1e22 and 1e-22)
    f = np.exp(np.arange(1-n, n, 2) * (0.5 * np.log(a))) # Scaling factor for each slice
    tmp = (np.resize(input, ((len(input) + n - 1) // n, n)) / f * (1. - a)).cumsum(axis=1) * f # Get ewm for each slice of length n

    # Add the last value of each previous slice to the next slice with corresponding scaling factor f and return result
    return np.resize(tmp + np.tensordot(np.append(input[0], np.roll(tmp.T[n-1], 1)[1:]), f * ((a) / f[0]), axes=0), len(input))

In [0]:
# input = tf.range(1,6,dtype=tf.float32)
# a = tf.constant(0.20)    # decay rate

input = [1.,2.,3.,4.,5.]
a = 0.20
tf.print("================= Input before calculating Exponentially moving Average =================== \n")
tf.print(input)
tf.print("================= Last Output after calculating Exponentially moving Average =================== \n")
output = task5(input,a)
tf.print(output[-1])

================= Input before calculating Exponentially moving Average =================== 

[1.0, 2.0, 3.0, 4.0, 5.0]
================= Last Output after calculating Exponentially moving Average =================== 

4.750399999999998


# Task 6

In [0]:
@tf.function
def task6(x,y,z):
  depth = x.shape
  x = tf.unstack(tf.reshape(x, [-1]))
  y = tf.unstack(tf.reshape(y, [-1]))
  z = tf.unstack(tf.reshape(z, [-1]))
  newarr = tf.TensorArray(dtype=tf.int32,size=0,dynamic_size=True,clear_after_read=False)
  # print(x)
  for i,m in enumerate(x):
    if (m % 2 == 0):
      newarr = newarr.write(i,y[i])  
    else:
       newarr = newarr.write(i,z[i]) 
  tf.print("================= Output after calculation =================== \n")
  tf.print(tf.reshape(newarr.stack(),shape=depth))

In [0]:
x = tf.random.uniform((2,3,2),minval=0,maxval=100,dtype=tf.dtypes.int32)
y = tf.random.uniform((2,3,2),minval=0,maxval=100,dtype=tf.dtypes.int32)
z = tf.random.uniform((2,3,2),minval=0,maxval=100,dtype=tf.dtypes.int32)
tf.print("================= Input x =================== \n")
tf.print(x,"\n")
tf.print("================= Input y =================== \n")
tf.print(y,"\n")
tf.print("================= Input z =================== \n")
tf.print(z,"\n")
task6(x,y,z)

================= Input x =================== 

[[[95 93]
  [0 54]
  [30 28]]

 [[53 22]
  [92 97]
  [41 85]]] 

================= Input y =================== 

[[[77 6]
  [34 65]
  [19 73]]

 [[81 44]
  [39 44]
  [45 53]]] 

================= Input z =================== 

[[[24 4]
  [87 10]
  [57 33]]

 [[93 54]
  [46 75]
  [14 22]]] 

================= Output after calculation =================== 

[[[24 4]
  [34 65]
  [19 73]]

 [[93 44]
  [39 75]
  [14 22]]]


# Task 7

In [0]:
@tf.function
def task7(arr):
  depth = arr.get_shape()
  if depth[-1] > 100:
    return 100
  elif depth[-1] <= 100 and depth[-1] > 44:
    return 12
  else:
    return 0

In [0]:
x = tf.random.uniform(shape=(4,6,101),minval=100,maxval=150)
result = task7(x)
tf.print("=========== Result after checking size of last dimension =============== \n")
tf.print(result)

=========== Result after checking size of last dimension =============== 

100


# Task 8 

In [0]:
i = tf.Variable(0,dtype=tf.int32)
j = tf.Variable(0,dtype=tf.int32)
k = tf.Variable(0,dtype=tf.int32)

def first():
  global i
  i = i+1
 
def second():
  global j
  j = j+1

def third():
  global k
  k = k+1

def task8(arr):
  global i,j,k
  depth = arr.get_shape()
  if depth[-1] > 100:
    first()
    return 100
  elif depth[-1] <= 100 and depth[-1] > 44:
    second()
    return 12
  else:
    third()
    return 0

In [0]:
x = tf.random.uniform(shape=(4,5,145),minval=100,maxval=150)
for m in tf.range(10):
   task8(x)
tf.print("=========== Global variable update for i =============== \n")
tf.print(i,j,k)

x = tf.random.uniform(shape=(4,5,45),minval=100,maxval=150)
for m in tf.range(15):
   task8(x)
tf.print("=========== Global variable update for j =============== \n")
tf.print(i,j,k)

x = tf.random.uniform(shape=(4,5,5),minval=100,maxval=150)
for m in tf.range(20):
   task8(x)
tf.print("=========== Global variable update for k =============== \n")
tf.print(i,j,k)

=========== Global variable update for i =============== 

10 0 0
=========== Global variable update for j =============== 

10 15 0
=========== Global variable update for k =============== 

10 15 20


When trying with tf.function , I am facing an error on tf.print(i,j,k) statement, 

Error : 'Tensor' object has no attribute '_datatype_enum'

# Task 9

In [0]:
@tf.function
def task9(x,y):
  result =  x[:,None]-y[None,:]   # [2,] - [,2] = [2,2]  element wise subtraction in x column elements are broadcasted and in y row elements are broadcasted
  # result = tf.broadcast_to([x-y],[2,2]) # not working as desired  [[-3 0] [-3 0]]
  # tf.print(result1,'\n')
  return result

In [0]:
x = tf.random.uniform((2,),minval=0,maxval=5,dtype=tf.dtypes.int32)
y = tf.random.uniform((2,),minval=0,maxval=10,dtype=tf.dtypes.int32)
tf.print("================= Input Tensor of shape (n,) =================== \n")
tf.print(x)
tf.print("================= Input Tensor of shape (n,) =================== \n")
tf.print(y)
tf.print("================= Output Tensor of shape (n,n) =================== \n")
output = task9(x,y)
tf.print(output)

================= Input Tensor of shape (n,) =================== 

[1 4]
================= Input Tensor of shape (n,) =================== 

[4 1]
================= Output Tensor of shape (n,n) =================== 

[[-3 0]
 [0 3]]


# Task 10

In [0]:
# Source :  https://stackoverflow.com/questions/42507030/implementing-attention-in-tensorflow

@tf.function
def task10(batch_size,time,features):
  # shape of sequence of encoder states h is batch x time x features 10 x 4 x 3
  encoder_hidden_state = tf.constant(np.random.randn(batch_size, time, features), tf.float32)

  # last decoder shape : batch x features  10 x 3
  s = tf.constant(np.random.randn(batch_size, features), tf.float32)

  W_HS = tf.random.uniform(shape = [features, features],minval=-0.03,maxval=0.03)
  w_alpha = tf.random.uniform(shape = [features],minval=-0.03,maxval=0.03)

  '''
  Einsum allows defining Tensors by defining their element-wise computation.Steps to convert the element-wise equation into the equation:
        1. remove variable names, brackets, and commas, (ik = sum_j ij * jk)
        2. replace "*" with ",", (ik = sum_j ij , jk)
        3. drop summation signs, and (ik = ij, jk)
        4. move the output to the right, while replacing "=" with "->". (ij,jk->ik)
    '''
  #  batch x time x features  -- tanh(W_HS^{encoder_hidden_state}encoder_hidden_state)
  M = tf.tanh(tf.einsum("aij,jk->aik", encoder_hidden_state, W_HS))

  # print(M)
  # batch_size x time        -- softmax(M w_alpha^T)
  alpha = tf.nn.softmax(tf.einsum("aij,j->ai", M, w_alpha))
  return alpha

In [0]:
batch_size = 6
time = 4
features = 3
tf.print("\n ================= Output attention matrix =================== \n")
output = task10(batch_size,time,features)
tf.print(output)
tf.print("\n ================= Output attention matrix shape (batch_size,time) =================== \n")
tf.print(output.shape)

================= Output attention matrix =================== 

[[0.250110447 0.24997738 0.249937311 0.249974921]
 [0.250029653 0.249999806 0.250055641 0.249914855]
 [0.250080794 0.249877632 0.249849096 0.250192434]
 [0.249993011 0.250065446 0.250213832 0.249727711]
 [0.250130713 0.249761537 0.249999359 0.250108391]
 [0.250097036 0.249748081 0.25039348 0.249761388]]
================= Output attention matrix shape (batch_size,time) =================== 

TensorShape([6, 4])
